print("Please follow these steps to calibrate the FermenTech digital hydrometer.")
print("A physical hydrometer is necessary to calibrate this sensor")
print("Insert the physical hydrometer into the brew")
print("Read the hydrometer scale at the lowest point of the liquid's surface")
print("Please input the physical hydrometer reading to three decimal places (example: 1.000)")
print("\n")
initial_specific_gravity = input("Input reading now: ")
